language: python

dist: xenial

services:
  - docker

install:
  - pip install coveralls

script:
  - make tests

after_success:
  - sed -i "s#/data#/home/travis/build/parkoview/wheel2deb#g" .coverage
  - coveralls